<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="HASSEN-HP" failures="1" tests="4" name="Test" time="0.114" errors="0" timestamp="2022-09-05T15:02:21 EDT">
  <testcase classname="listeners.Runner" name="test2" time="0.017">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="listeners.Runner" name="test2" time="0.003">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="listeners.Runner" name="test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at listeners.Runner.test2(Runner.java:40)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="listeners.Runner" name="test3" time="0.002"/>
  <testcase classname="listeners.Runner" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Test -->
