<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20753" started-at="2019-01-16T03:28:37Z" finished-at="2019-01-16T03:28:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20753" started-at="2019-01-16T03:28:37Z" finished-at="2019-01-16T03:28:57Z">
      <class name="HubSpotTests.HubSpotLoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:HubSpotTests.HubSpotLoginTest@5e3a8624]" name="setUp" is-config="true" duration-ms="5060" started-at="2019-01-16T03:28:37Z" finished-at="2019-01-16T03:28:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:HubSpotTests.HubSpotLoginTest@5e3a8624]" name="loginTest" duration-ms="7294" started-at="2019-01-16T03:28:42Z" finished-at="2019-01-16T03:28:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Reports dashboardXX] but found [Reports dashboard]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Reports dashboardXX] but found [Reports dashboard]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at HubSpotTests.HubSpotLoginTest.loginTest(HubSpotLoginTest.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:HubSpotTests.HubSpotLoginTest@5e3a8624]" name="tearDown" is-config="true" duration-ms="115" started-at="2019-01-16T03:28:49Z" finished-at="2019-01-16T03:28:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:HubSpotTests.HubSpotLoginTest@5e3a8624]" name="setUp" is-config="true" duration-ms="4344" started-at="2019-01-16T03:28:49Z" finished-at="2019-01-16T03:28:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyLoginButtonTest()[pri:0, instance:HubSpotTests.HubSpotLoginTest@5e3a8624]" name="verifyLoginButtonTest" duration-ms="37" started-at="2019-01-16T03:28:53Z" finished-at="2019-01-16T03:28:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginButtonTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:HubSpotTests.HubSpotLoginTest@5e3a8624]" name="tearDown" is-config="true" duration-ms="101" started-at="2019-01-16T03:28:53Z" finished-at="2019-01-16T03:28:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:HubSpotTests.HubSpotLoginTest@5e3a8624]" name="setUp" is-config="true" duration-ms="3669" started-at="2019-01-16T03:28:54Z" finished-at="2019-01-16T03:28:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyLoginPageTitleTest()[pri:0, instance:HubSpotTests.HubSpotLoginTest@5e3a8624]" name="verifyLoginPageTitleTest" duration-ms="9" started-at="2019-01-16T03:28:57Z" finished-at="2019-01-16T03:28:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[title is not equal expected [HubSpot LoginXX] but found [HubSpot Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: title is not equal expected [HubSpot LoginXX] but found [HubSpot Login]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at HubSpotTests.HubSpotLoginTest.verifyLoginPageTitleTest(HubSpotLoginTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:HubSpotTests.HubSpotLoginTest@5e3a8624]" name="tearDown" is-config="true" duration-ms="98" started-at="2019-01-16T03:28:57Z" finished-at="2019-01-16T03:28:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- HubSpotTests.HubSpotLoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
